name: Build ZuluIDE firmware

on: 
  push:
  workflow_dispatch:

jobs:
  build_firmware:
    name: Build firmware on Ubuntu 22.04
    runs-on: ubuntu-22.04
    
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
        with:
          path: CUEParser
          fetch-depth: "0"
            
      - name: Run tests firmware
        run: |
          cd CUEParser/test
          make
